services:
  db:
    container_name: db_graph
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - ${MYSQLDB_PORT}:${MYSQLDB_PORT}
    volumes:
      - sql_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - graph-sql-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_graph
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /usr/src/app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - graph-sql-network

  frontend:
    container_name: frontend_graph
    restart: unless-stopped
    build:
      context: ../frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://host.docker.internal:8080
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - graph-sql-network

networks:
  graph-sql-network:
    driver: bridge
volumes:
  sql_volume:
