services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - 3307:${MYSQLDB_PORT}
    volumes:
      - rest_volume:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - rest-network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - rest-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - rest-network

networks:
  rest-network:
    driver: bridge
volumes:
  rest_volume:
